FROM golang:1.11

ENV DEP_VERSION=0.5.0 \
    DEP_SHA256SUM=287b08291e14f1fae8ba44374b26a2b12eb941af3497ed0ca649253e21ba2f83

RUN set -x \
 && dep_binary=/usr/local/bin/dep \
 && curl -fsSL "https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64" -o $dep_binary \
 && echo "${DEP_SHA256SUM} ${dep_binary}" | sha256sum -c - \
 && chmod +x $dep_binary \
 && dep version

RUN go get github.com/jstemmer/go-junit-report
