version: 2

jobs:
  build:
    docker:
      - image: ahaines/envy-build:1

    working_directory: /go/src/github.com/haines/envy

    steps:
      - checkout

      - restore_cache:
          key: vendor:v1:{{checksum "Gopkg.lock"}}

      - run:
          name: 🚚 Get dependencies
          command: make get

      - save_cache:
          key: vendor:v1:{{checksum "Gopkg.lock"}}
          paths:
            - vendor

      - run:
          name: 💅 Lint code
          command: make check

      - run:
          name: 📦 Build executable
          command: make build

      - run:
          name: 🔬 Run tests
          command: make test

      - store_test_results:
          path: target
