version: 2

jobs:
  build:
    docker:
      - image: ahaines/envy-circleci:1

    working_directory: /go/src/github.com/haines/envy

    steps:
      - checkout

      - run:
          name: 🚚 Get dependencies
          command: make get

      - run:
          name: 💅 Lint code
          command: make check

      - run:
          name: 📦 Build executable
          command: make build

      - run:
          name: 🔬 Run tests
          command: make test
